$(document).ready(function() {
  function fetchCityData(cityId) {
    var cityUrl = "data/cities/" + cityId + ".json";
    var ids = ["city-name", "city-population", "city-violent-crime",
            "city-rape", "city-murders", "city-robbery", 
            "city-vehicle-theft"];
    var fields = ["name", "population", "violent crime",
            "forcible rape", "murder and nonnegligent manslaughter",
            "robbery", "vehicle-theft"];
    var template = "<td>{0}</td>";

    $.getJSON(cityUrl, function(data) {
      for (var i = 0; i < fields.length; i++) {
        var property = fields[i];
        var value = data[property]
        var el = "<td class='" + data.id + "'>" + value + "</td>;"
        $(el).appendTo("#" + ids[i]);
      }
    });  
  };

  var cities = [
    { num: 1, city: "New York, New York", id: "new_york_new_york" },
    { num: 2, city: "Los Angeles, California", id: "los_angeles_california" },
    { num: 3, city: "Chicago, Illinois", id: "chicago_illinois" },
    { num: 4, city: "Houston, Texas", id: "houston_texas" },
    { num: 5, city: "Philadelphia, Pennsylvania", id: "philadelphia_pennsylvania" },
    { num: 6, city: "Phoenix, Arizona", id: "phoenix_arizona" },
    { num: 7, city: "San Antonio, Texas", id: "san_antonio_texas" },
    { num: 8, city: "San Diego, California", id: "san_diego_california" },
    { num: 9, city: "Dallas, Texas", id: "dallas_texas" },
    { num: 10, city: "San Jose, California", id: "san_jose_california" },
    { num: 11, city: "Austin, Texas", id: "austin_texas" },
    { num: 12, city: "Jacksonville, Florida", id: "jacksonville_florida" },
    { num: 13, city: "Indianapolis, Indiana", id: "indianapolis_indiana" },
    { num: 14, city: "San Francisco, California", id: "san_francisco_california" },
    { num: 15, city: "Columbus, Ohio", id: "columbus_ohio" },
    { num: 16, city: "Fort Worth, Texas", id: "fort_worth_texas" },
    { num: 17, city: "Charlotte, North Carolina", id: "charlotte_north_carolina" },
    { num: 18, city: "Detroit, Michigan", id: "detroit_michigan" },
    { num: 19, city: "El Paso, Texas", id: "el_paso_texas" },
    { num: 20, city: "Memphis, Tennessee", id: "memphis_tennessee" },
    { num: 21, city: "Boston, Massachusetts", id: "boston_massachusetts" },
    { num: 22, city: "Seattle, Washington", id: "seattle_washington" },
    { num: 23, city: "Denver, Colorado", id: "denver_colorado" },
    { num: 24, city: "Washington, District of Columbia", id: "washington_district_of_columbia" },
    { num: 25, city: "Nashville, Tennessee", id: "nashville_tennessee" },
    { num: 26, city: "Baltimore, Maryland", id: "baltimore_maryland" },
    { num: 27, city: "Louisville,	Kentucky", id: "louisville_kentucky" },
    { num: 28, city: "Portland, Oregon", id: "portland_oregon" },
    { num: 29, city: "Oklahoma City, Oklahoma", id: "oklahoma_city_oklahoma" },
    { num: 30, city: "Milwaukee, Wisconsin", id: "milwaukee_wisconsin" },
    { num: 31, city: "Las Vegas, Nevada", id: "las_vegas_nevada" },
    { num: 32, city: "Albuquerque, New Mexico", id: "albuquerque_new_mexico" },
    { num: 33, city: "Tucson, Arizona", id: "tucson_arizona" },
    { num: 34, city: "Fresno, California", id: "fresno_california" },
    { num: 35, city: "Sacramento, California", id: "sacramento_california" },
    { num: 36, city: "Long Beach, California", id: "long_beach_california" },
    { num: 37, city: "Kansas City, Missouri", id: "kansas_city_missouri" },
    { num: 38, city: "Mesa, Arizona", id: "mesa_arizona" },
    { num: 39, city: "Virginia Beach, Virginia", id: "virginia_beach_virginia" },
    { num: 40, city: "Atlanta, Georgia", id: "atlanta_georgia" },
    { num: 41, city: "Colorado Springs, Colorado", id: "colorado_springs_colorado" },
    { num: 42, city: "Raleigh, North Carolina", id: "raleigh_north_carolina" },
    { num: 43, city: "Omaha, Nebraska", id: "omaha_nebraska" },
    { num: 44, city: "Miami, Florida", id: "miami_florida" },
    { num: 45, city: "Oakland, California", id: "oakland_california" },
    { num: 46, city: "Tulsa, Oklahoma", id: "tulsa_oklahoma" },
    { num: 47, city: "Minneapolis, Minnesota", id: "minneapolis_minnesota" },
    { num: 48, city: "Cleveland, Ohio", id: "cleveland_ohio" },
    { num: 49, city: "Wichita, Kansas", id: "wichita_kansas" },
    { num: 50, city: "Arlington, Texas", id: "arlington_texas" },
    { num: 51, city: "New Orleans, Louisiana", id: "new_orleans_louisiana" },
    { num: 52, city: "Bakersfield, California", id: "bakersfield_california" },
    { num: 53, city: "Tampa, Florida", id: "tampa_florida" },
    { num: 54, city: "Honolulu,	Hawaii", id: "honolulu_hawaii" },
    { num: 55, city: "Anaheim, California", id: "anaheim_california" },
    { num: 56, city: "Aurora, Colorado", id: "aurora_colorado" },
    { num: 57, city: "Santa Ana, California", id: "santa_ana_california" },
    { num: 58, city: "St. Louis, Missouri", id: "st_louis_missouri" },
    { num: 59, city: "Riverside, California", id: "riverside_california" },
    { num: 60, city: "Corpus Christi, Texas", id: "corpus_christi_texas" },
    { num: 61, city: "Pittsburgh, Pennsylvania", id: "pittsburgh_pennsylvania" },
    { num: 62, city: "Lexington-Fayette, Kentucky", id: "lexington_fayette_kentucky" },
    { num: 63, city: "Anchorage, Alaska", id: "anchorage_alaska" },
    { num: 64, city: "Stockton, California", id: "stockton_california" },
    { num: 65, city: "Cincinnati, Ohio", id: "cincinnati_ohio" },
    { num: 66, city: "St. Paul, Minnesota", id: "st_paul_minnesota" },
    { num: 67, city: "Toledo, Ohio", id: "toledo_ohio" },
    { num: 68, city: "Newark, New Jersey", id: "newark_new_jersey" },
    { num: 69, city: "Greensboro, North Carolina", id: "greensboro_north_carolina" },
    { num: 70, city: "Plano, Texas", id: "plano_texas" },
    { num: 71, city: "Henderson, Nevada", id: "henderson_nevada" },
    { num: 72, city: "Lincoln, Nebraska", id: "lincoln_nebraska" },
    { num: 73, city: "Buffalo, New York", id: "buffalo_new_york" },
    { num: 74, city: "Fort Wayne, Indiana", id: "fort_wayne_indiana" },
    { num: 75, city: "Jersey City, New Jersey", id: "jersey_city_new_jersey" },
    { num: 76, city: "Chula Vista, California", id: "chula_vista_california" },
    { num: 77, city: "Orlando, Florida", id: "orlando_florida" },
    { num: 78, city: "St. Petersburg, Florida", id: "st_petersburg_florida" },
    { num: 79, city: "Norfolk, Virginia", id: "norfolk_virginia" },
    { num: 80, city: "Chandler, Arizona", id: "chandler_arizona" },
    { num: 81, city: "Laredo, Texas", id: "laredo_texas" },
    { num: 82, city: "Madison, Wisconsin", id: "madison_wisconsin" },
    { num: 83, city: "Durham, North Carolina", id: "durham_north_carolina" },
    { num: 84, city: "Lubbock, Texas", id: "lubbock_texas" },
    { num: 85, city: "Winston-Salem, North Carolina", id: "winston_salem_north_carolina" },
    { num: 86, city: "Garland, Texas", id: "garland_texas" },
    { num: 87, city: "Glendale, Arizona", id: "glendale_arizona" },
    { num: 88, city: "Hialeah, Florida", id: "hialeah_florida" },
    { num: 89, city: "Reno, Nevada", id: "reno_nevada" },
    { num: 90, city: "Baton Rouge, Louisiana", id: "baton_rouge_louisiana" },
    { num: 91, city: "Irvine, California", id: "irvine_california" },
    { num: 92, city: "Chesapeake, Virginia", id: "chesapeake_virginia" },
    { num: 93, city: "Irving, Texas", id: "irving_texas" },
    { num: 94, city: "Scottsdale, Arizona", id: "scottsdale_arizona" },
    { num: 95, city: "North Las Vegas, Nevada", id: "north_las_vegas_nevada" },
    { num: 96, city: "Fremont, California", id: "fremont_california" },
    { num: 97, city: "Gilbert, Arizona", id: "gilbert_arizona" },
    { num: 98, city: "San Bernardino, California", id: "san_bernardino_california" },
    { num: 99, city: "Boise City, Idaho", id: "boise_city_idaho" },
    { num: 100, city: "Birmingham, Alabama", id: "birmingham_alabama" },
    { num: 101, city: "Rochester, New York", id: "rochester_new_york" },
    { num: 102, city: "Richmond, Virginia", id: "richmond_virginia" },
    { num: 103, city: "Spokane, Washington", id: "spokane_washington" },
    { num: 104, city: "Des Moines, Iowa", id: "des_moines_iowa" },
    { num: 105, city: "Montgomery, Alabama", id: "montgomery_alabama" },
    { num: 106, city: "Modesto, California", id: "modesto_california" },
    { num: 107, city: "Fayetteville, North Carolina", id: "fayetteville_north_carolina" },
    { num: 108, city: "Tacoma, Washington", id: "tacoma_washington" },
    { num: 109, city: "Shreveport, Louisiana", id: "shreveport_louisiana" },
    { num: 110, city: "Fontana, California", id: "fontana_california" },
    { num: 111, city: "Oxnard, California", id: "oxnard_california" },
    { num: 112, city: "Aurora, Illinois", id: "aurora_illinois" },
    { num: 113, city: "Moreno Valley, California", id: "moreno_valley_california" },
    { num: 114, city: "Akron, Ohio", id: "akron_ohio" },
    { num: 115, city: "Yonkers, New York", id: "yonkers_new_york" },
    { num: 116, city: "Columbus, Georgia", id: "columbus_georgia" },
    { num: 117, city: "Augusta-Richmond, Georgia", id: "augusta_richmond_georgia" },
    { num: 118, city: "Little Rock, Arkansas", id: "little_rock_arkansas" },
    { num: 119, city: "Amarillo, Texas", id: "amarillo_texas" },
    { num: 120, city: "Mobile, Alabama", id: "mobile_alabama" },
    { num: 121, city: "Huntington Beach, California", id: "huntington_beach_california" },
    { num: 122, city: "Glendale, California", id: "glendale_california" },
    { num: 123, city: "Grand Rapids, Michigan", id: "grand_rapids_michigan" },
    { num: 124, city: "Salt Lake City, Utah", id: "salt_lake_city_utah" },
    { num: 125, city: "Tallahassee, Florida", id: "tallahassee_florida" },
    { num: 126, city: "Huntsville, Alabama", id: "huntsville_alabama" },
    { num: 127, city: "Worcester, Massachusetts", id: "worcester_massachusetts" },
    { num: 128, city: "Knoxville, Tennessee", id: "knoxville_tennessee" },
    { num: 129, city: "Grand Prairie, Texas", id: "grand_prairie_texas" },
    { num: 130, city: "Newport News, Virginia", id: "newport_news_virginia" },
    { num: 131, city: "Brownsville, Texas", id: "brownsville_texas" },
    { num: 132, city: "Santa Clarita, California", id: "santa_clarita_california" },
    { num: 133, city: "Overland Park, Kansas", id: "overland_park_kansas" },
    { num: 134, city: "Providence, Rhode Island", id: "providence_rhode_island" },
    { num: 135, city: "Jackson, Mississippi", id: "jackson_mississippi" },
    { num: 136, city: "Garden Grove, California", id: "garden_grove_california" },
    { num: 137, city: "Oceanside, California", id: "oceanside_california" },
    { num: 138, city: "Chattanooga, Tennessee", id: "chattanooga_tennessee" },
    { num: 139, city: "Fort Lauderdale, Florida", id: "fort_lauderdale_florida" },
    { num: 140, city: "Rancho Cucamonga, California", id: "rancho_cucamonga_california" },
    { num: 141, city: "Santa Rosa, California", id: "santa_rosa_california" },
    { num: 142, city: "Port St. Lucie, Florida", id: "port_st_lucie_florida" },
    { num: 143, city: "Ontario, California", id: "ontario_california" },
    { num: 144, city: "Tempe, Arizona", id: "tempe_arizona" },
    { num: 145, city: "Vancouver, Washington", id: "vancouver_washington" },
    { num: 146, city: "Springfield, Missouri", id: "springfield_missouri" },
    { num: 147, city: "Cape Coral, Florida", id: "cape_coral_florida" },
    { num: 148, city: "Pembroke Pines, Florida", id: "pembroke_pines_florida" },
    { num: 149, city: "Sioux Falls, South Dakota", id: "sioux_falls_south_dakota" },
    { num: 150, city: "Peoria, Arizona", id: "peoria_arizona" },
    { num: 151, city: "Lancaster, California", id: "lancaster_california" },
    { num: 152, city: "Elk Grove, California", id: "elk_grove_california" },
    { num: 153, city: "Corona, California", id: "corona_california" },
    { num: 154, city: "Eugene, Oregon", id: "eugene_oregon" },
    { num: 155, city: "Salem, Oregon", id: "salem_oregon" },
    { num: 156, city: "Palmdale, California", id: "palmdale_california" },
    { num: 157, city: "Salinas, California", id: "salinas_california" },
    { num: 158, city: "Springfield, Massachusetts", id: "springfield_massachusetts" },
    { num: 159, city: "Pasadena, Texas", id: "pasadena_texas" },
    { num: 160, city: "Rockford, Illinois", id: "rockford_illinois" },
    { num: 161, city: "Pomona, California", id: "pomona_california" },
    { num: 162, city: "Hayward, California", id: "hayward_california" },
    { num: 163, city: "Fort Collins, Colorado", id: "fort_collins_colorado" },
    { num: 164, city: "Joliet, Illinois", id: "joliet_illinois" },
    { num: 165, city: "Escondido, California", id: "escondido_california" },
    { num: 166, city: "Kansas City, Kansas", id: "kansas_city_kansas" },
    { num: 167, city: "Torrance, California", id: "torrance_california" },
    { num: 168, city: "Bridgeport, Connecticut", id: "bridgeport_connecticut" },
    { num: 169, city: "Alexandria, Virginia", id: "alexandria_virginia" },
    { num: 170, city: "Sunnyvale, California", id: "sunnyvale_california" },
    { num: 171, city: "Cary, North Carolina", id: "cary_north_carolina" },
    { num: 172, city: "Lakewood, Colorado", id: "lakewood_colorado" },
    { num: 173, city: "Hollywood, Florida", id: "hollywood_florida" },
    { num: 174, city: "Paterson, New Jersey", id: "paterson_new_jersey" },
    { num: 175, city: "Syracuse, New York", id: "syracuse_new_york" },
    { num: 176, city: "Naperville, Illinois", id: "naperville_illinois" },
    { num: 177, city: "McKinney, Texas", id: "mckinney_texas" },
    { num: 178, city: "Mesquite, Texas", id: "mesquite_texas" },
    { num: 179, city: "Clarksville, Tennessee", id: "clarksville_tennessee" },
    { num: 180, city: "Savannah, Georgia", id: "savannah_georgia" },
    { num: 181, city: "Dayton, Ohio", id: "dayton_ohio" },
    { num: 182, city: "Orange, California", id: "orange_california" },
    { num: 183, city: "Fullerton, California", id: "fullerton_california" },
    { num: 184, city: "Pasadena, California", id: "pasadena_california" },
    { num: 185, city: "Hampton, Virginia", id: "hampton_virginia" },
    { num: 186, city: "McAllen, Texas", id: "mcallen_texas" },
    { num: 187, city: "Killeen, Texas", id: "killeen_texas" },
    { num: 188, city: "Warren, Michigan", id: "warren_michigan" },
    { num: 189, city: "West Valley City, Utah", id: "west_valley_city_utah" },
    { num: 190, city: "Columbia, South Carolina", id: "columbia_south_carolina" },
    { num: 191, city: "New Haven, Connecticut", id: "new_haven_connecticut" },
    { num: 192, city: "Sterling Heights, Michigan", id: "sterling_heights_michigan" },
    { num: 193, city: "Olathe, Kansas", id: "olathe_kansas" },
    { num: 194, city: "Miramar, Florida", id: "miramar_florida" },
    { num: 195, city: "Thousand Oaks, California", id: "thousand_oaks_california" },
    { num: 196, city: "Frisco, Texas", id: "frisco_texas" },
    { num: 197, city: "Cedar Rapids, Iowa", id: "cedar_rapids_iowa" },
    { num: 198, city: "Topeka, Kansas", id: "topeka_kansas" },
    { num: 199, city: "Visalia, California", id: "visalia_california" },
    { num: 200, city: "Waco, Texas", id: "waco_texas" },
    { num: 201, city: "Elizabeth, New Jersey", id: "elizabeth_new_jersey" },
    { num: 202, city: "Bellevue, Washington", id: "bellevue_washington" },
    { num: 203, city: "Gainesville, Florida", id: "gainesville_florida" },
    { num: 204, city: "Simi Valley, California", id: "simi_valley_california" },
    { num: 205, city: "Charleston, South Carolina", id: "charleston_south_carolina" },
    { num: 206, city: "Carrollton, Texas", id: "carrollton_texas" },
    { num: 207, city: "Coral Springs, Florida", id: "coral_springs_florida" },
    { num: 208, city: "Stamford, Connecticut", id: "stamford_connecticut" },
    { num: 209, city: "Hartford, Connecticut", id: "hartford_connecticut" },
    { num: 210, city: "Concord, California", id: "concord_california" },
    { num: 211, city: "Roseville, California", id: "roseville_california" },
    { num: 212, city: "Thornton, Colorado", id: "thornton_colorado" },
    { num: 213, city: "Kent, Washington", id: "kent_washington" },
    { num: 214, city: "Lafayette, Louisiana", id: "lafayette_louisiana" },
    { num: 215, city: "Surprise, Arizona", id: "surprise_arizona" },
    { num: 216, city: "Denton, Texas", id: "denton_texas" },
    { num: 217, city: "Victorville, California", id: "victorville_california" },
    { num: 218, city: "Evansville, Indiana", id: "evansville_indiana" },
    { num: 219, city: "Midland, Texas", id: "midland_texas" },
    { num: 220, city: "Santa Clara, California", id: "santa_clara_california" },
    { num: 221, city: "Athens, Georgia", id: "athens_georgia" },
    { num: 222, city: "Allentown, Pennsylvania", id: "allentown_pennsylvania" },
    { num: 223, city: "Abilene, Texas", id: "abilene_texas" },
    { num: 224, city: "Beaumont, Texas", id: "beaumont_texas" },
    { num: 225, city: "Vallejo, California", id: "vallejo_california" },
    { num: 226, city: "Independence, Missouri", id: "independence_missouri" },
    { num: 227, city: "Springfield, Illinois", id: "springfield_illinois" },
    { num: 228, city: "Ann Arbor, Michigan", id: "ann_arbor_michigan" },
    { num: 229, city: "Provo, Utah", id: "provo_utah" },
    { num: 230, city: "Peoria, Illinois", id: "peoria_illinois" },
    { num: 231, city: "Norman, Oklahoma", id: "norman_oklahoma" },
    { num: 232, city: "Berkeley, California", id: "berkeley_california" },
    { num: 233, city: "El Monte, California", id: "el_monte_california" },
    { num: 234, city: "Murfreesboro, Tennessee", id: "murfreesboro_tennessee" },
    { num: 235, city: "Lansing, Michigan", id: "lansing_michigan" },
    { num: 236, city: "Columbia, Missouri", id: "columbia_missouri" },
    { num: 237, city: "Downey, California", id: "downey_california" },
    { num: 238, city: "Costa Mesa, California", id: "costa_mesa_california" },
    { num: 239, city: "Inglewood, California", id: "inglewood_california" },
    { num: 240, city: "Miami Gardens, Florida", id: "miami_gardens_florida" },
    { num: 241, city: "Manchester, New Hampshire", id: "manchester_new_hampshire" },
    { num: 242, city: "Elgin, Illinois", id: "elgin_illinois" },
    { num: 243, city: "Wilmington, North Carolina", id: "wilmington_north_carolina" },
    { num: 244, city: "Waterbury, Connecticut", id: "waterbury_connecticut" },
    { num: 245, city: "Fargo, North Dakota", id: "fargo_north_dakota" },
    { num: 246, city: "Arvada, Colorado", id: "arvada_colorado" },
    { num: 247, city: "Carlsbad, California", id: "carlsbad_california" },
    { num: 248, city: "Westminster, Colorado", id: "westminster_colorado" },
    { num: 249, city: "Rochester, Minnesota", id: "rochester_minnesota" },
    { num: 250, city: "Gresham, Oregon", id: "gresham_oregon" },
    { num: 251, city: "Clearwater, Florida", id: "clearwater_florida" },
    { num: 252, city: "Lowell, Massachusetts", id: "lowell_massachusetts" },
    { num: 253, city: "West Jordan, Utah", id: "west_jordan_utah" },
    { num: 254, city: "Pueblo, Colorado", id: "pueblo_colorado" },
    { num: 255, city: "San Buenaventura, California", id: "san_buenaventura_california" },
    { num: 256, city: "Fairfield, California", id: "fairfield_california" },
    { num: 257, city: "West Covina, California", id: "west_covina_california" },
    { num: 258, city: "Billings, Montana", id: "billings_montana" },
    { num: 259, city: "Murrieta, California", id: "murrieta_california" },
    { num: 260, city: "High Point, North Carolina", id: "high_point_north_carolina" },
    { num: 261, city: "Round Rock, Texas", id: "round_rock_texas" },
    { num: 262, city: "Richmond, California", id: "richmond_california" },
    { num: 263, city: "Cambridge, Massachusetts", id: "cambridge_massachusetts" },
    { num: 264, city: "Norwalk, California", id: "norwalk_california" },
    { num: 265, city: "Odessa, Texas", id: "odessa_texas" },
    { num: 266, city: "Antioch, California", id: "antioch_california" },
    { num: 267, city: "Temecula, California", id: "temecula_california" },
    { num: 268, city: "Green Bay, Wisconsin", id: "green_bay_wisconsin" },
    { num: 269, city: "Everett, Washington", id: "everett_washington" },
    { num: 270, city: "Wichita Falls, Texas", id: "wichita_falls_texas" },
    { num: 271, city: "Burbank, California", id: "burbank_california" },
    { num: 272, city: "Palm Bay, Florida", id: "palm_bay_florida" },
    { num: 273, city: "Centennial, Colorado", id: "centennial_colorado" },
    { num: 274, city: "Daly City, California", id: "daly_city_california" },
    { num: 275, city: "Richardson, Texas", id: "richardson_texas" },
    { num: 276, city: "Pompano Beach, Florida", id: "pompano_beach_florida" },
    { num: 277, city: "Broken Arrow, Oklahoma", id: "broken_arrow_oklahoma" },
    { num: 278, city: "North Charleston, South Carolina", id: "north_charleston_south_carolina" },
    { num: 279, city: "West Palm Beach, Florida", id: "west_palm_beach_florida" },
    { num: 280, city: "Boulder, Colorado", id: "boulder_colorado" },
    { num: 281, city: "Rialto, California", id: "rialto_california" },
    { num: 282, city: "Santa Maria, California", id: "santa_maria_california" },
    { num: 283, city: "El Cajon, California", id: "el_cajon_california" },
    { num: 284, city: "Davenport, Iowa", id: "davenport_iowa" },
    { num: 285, city: "Las Cruces, New Mexico", id: "las_cruces_new_mexico" },
    { num: 286, city: "Erie, Pennsylvania", id: "erie_pennsylvania" },
    { num: 287, city: "South Bend, Indiana", id: "south_bend_indiana" },
    { num: 288, city: "Flint, Michigan", id: "flint_michigan" },
    { num: 289, city: "Kenosha, Wisconsin", id: "kenosha_wisconsin" },
    { num: 290, city: "Lakeland, Florida", id: "lakeland_florida" },
    { num: 291, city: "San Mateo, California", id: "san_mateo_california" },
    { num: 292, city: "Lewisville, Texas", id: "lewisville_texas" },
    { num: 293, city: "Sandy Springs, Georgia", id: "sandy_springs_georgia" },
    { num: 294, city: "Tyler, Texas", id: "tyler_texas" },
    { num: 295, city: "Clovis, California", id: "clovis_california" },
    { num: 296, city: "Lawton, Oklahoma", id: "lawton_oklahoma" },
    { num: 297, city: "Albany, New York", id: "albany_new_york" },
    { num: 298, city: "College Station, Texas", id: "college_station_texas" },
    { num: 299, city: "Compton, California", id: "compton_california" },
    { num: 300, city: "Roanoke, Virginia", id: "roanoke_virginia" },
];

  function addCity(city) {
    fetchCityData(city.id);
  };

  function deleteCity(city) {
    $("." + city.id).remove(); 
  };

  options = { 
    hintText: "Type in a city", 
    animateDropdown: false,
    searchDelay: 100,
    tokenLimit: 4,
    resultsLimit: 5,
    preventDuplicates: true,
    propertyToSearch: "city",
    onAdd: addCity,
    onDelete: deleteCity
  };

  $("#searchbar").tokenInput(cities, options);
});

