$(document).ready(function() {
  var cities = [
    { id: 1, city: "New York, New York", keyword: "new_york_new_york" },
    { id: 2, city: "Los Angeles, California", keyword: "los_angeles_california" },
    { id: 3, city: "Chicago, Illinois", keyword: "chicago_illinois" },
    { id: 4, city: "Houston, Texas", keyword: "houston_texas" },
    { id: 5, city: "Philadelphia, Pennsylvania", keyword: "philadelphia_pennsylvania" },
    { id: 6, city: "Phoenix, Arizona", keyword: "phoenix_arizona" },
    { id: 7, city: "San Antonio, Texas", keyword: "san_antonio_texas" },
    { id: 8, city: "San Diego, California", keyword: "san_diego_california" },
    { id: 9, city: "Dallas, Texas", keyword: "dallas_texas" },
    { id: 10, city: "San Jose, California", keyword: "san_jose_california" },
    { id: 11, city: "Austin, Texas", keyword: "austin_texas" },
    { id: 12, city: "Jacksonville, Florida", keyword: "jacksonville_florida" },
    { id: 13, city: "Indianapolis, Indiana", keyword: "indianapolis_indiana" },
    { id: 14, city: "San Francisco, California", keyword: "san_francisco_california" },
    { id: 15, city: "Columbus, Ohio", keyword: "columbus_ohio" },
    { id: 16, city: "Fort Worth, Texas", keyword: "fort_worth_texas" },
    { id: 17, city: "Charlotte, North Carolina", keyword: "charlotte_north_carolina" },
    { id: 18, city: "Detroit, Michigan", keyword: "detroit_michigan" },
    { id: 19, city: "El Paso, Texas", keyword: "el_paso_texas" },
    { id: 20, city: "Memphis, Tennessee", keyword: "memphis_tennessee" },
    { id: 21, city: "Boston, Massachusetts", keyword: "boston_massachusetts" },
    { id: 22, city: "Seattle, Washington", keyword: "seattle_washington" },
    { id: 23, city: "Denver, Colorado", keyword: "denver_colorado" },
    { id: 24, city: "Washington, District of Columbia", keyword: "washington_district_of_columbia" },
    { id: 25, city: "Nashville, Tennessee", keyword: "nashville_tennessee" },
    { id: 26, city: "Baltimore, Maryland", keyword: "baltimore_maryland" },
    { id: 27, city: "Louisville,	Kentucky", keyword: "louisville_kentucky" },
    { id: 28, city: "Portland, Oregon", keyword: "portland_oregon" },
    { id: 29, city: "Oklahoma City, Oklahoma", keyword: "oklahoma_city_oklahoma" },
    { id: 30, city: "Milwaukee, Wisconsin", keyword: "milwaukee_wisconsin" },
    { id: 31, city: "Las Vegas, Nevada", keyword: "las_vegas_nevada" },
    { id: 32, city: "Albuquerque, New Mexico", keyword: "albuquerque_new_mexico" },
    { id: 33, city: "Tucson, Arizona", keyword: "tucson_arizona" },
    { id: 34, city: "Fresno, California", keyword: "fresno_california" },
    { id: 35, city: "Sacramento, California", keyword: "sacramento_california" },
    { id: 36, city: "Long Beach, California", keyword: "long_beach_california" },
    { id: 37, city: "Kansas City, Missouri", keyword: "kansas_city_missouri" },
    { id: 38, city: "Mesa, Arizona", keyword: "mesa_arizona" },
    { id: 39, city: "Virginia Beach, Virginia", keyword: "virginia_beach_virginia" },
    { id: 40, city: "Atlanta, Georgia", keyword: "atlanta_georgia" },
    { id: 41, city: "Colorado Springs, Colorado", keyword: "colorado_springs_colorado" },
    { id: 42, city: "Raleigh, North Carolina", keyword: "raleigh_north_carolina" },
    { id: 43, city: "Omaha, Nebraska", keyword: "omaha_nebraska" },
    { id: 44, city: "Miami, Florida", keyword: "miami_florida" },
    { id: 45, city: "Oakland, California", keyword: "oakland_california" },
    { id: 46, city: "Tulsa, Oklahoma", keyword: "tulsa_oklahoma" },
    { id: 47, city: "Minneapolis, Minnesota", keyword: "minneapolis_minnesota" },
    { id: 48, city: "Cleveland, Ohio", keyword: "cleveland_ohio" },
    { id: 49, city: "Wichita, Kansas", keyword: "wichita_kansas" },
    { id: 50, city: "Arlington, Texas", keyword: "arlington_texas" },
    { id: 51, city: "New Orleans, Louisiana", keyword: "new_orleans_louisiana" },
    { id: 52, city: "Bakersfield, California", keyword: "bakersfield_california" },
    { id: 53, city: "Tampa, Florida", keyword: "tampa_florida" },
    { id: 54, city: "Honolulu,	Hawaii", keyword: "honolulu_hawaii" },
    { id: 55, city: "Anaheim, California", keyword: "anaheim_california" },
    { id: 56, city: "Aurora, Colorado", keyword: "aurora_colorado" },
    { id: 57, city: "Santa Ana, California", keyword: "santa_ana_california" },
    { id: 58, city: "St. Louis, Missouri", keyword: "st_louis_missouri" },
    { id: 59, city: "Riverside, California", keyword: "riverside_california" },
    { id: 60, city: "Corpus Christi, Texas", keyword: "corpus_christi_texas" },
    { id: 61, city: "Pittsburgh, Pennsylvania", keyword: "pittsburgh_pennsylvania" },
    { id: 62, city: "Lexington-Fayette, Kentucky", keyword: "lexington_fayette_kentucky" },
    { id: 63, city: "Anchorage, Alaska", keyword: "anchorage_alaska" },
    { id: 64, city: "Stockton, California", keyword: "stockton_california" },
    { id: 65, city: "Cincinnati, Ohio", keyword: "cincinnati_ohio" },
    { id: 66, city: "St. Paul, Minnesota", keyword: "st_paul_minnesota" },
    { id: 67, city: "Toledo, Ohio", keyword: "toledo_ohio" },
    { id: 68, city: "Newark, New Jersey", keyword: "newark_new_jersey" },
    { id: 69, city: "Greensboro, North Carolina", keyword: "greensboro_north_carolina" },
    { id: 70, city: "Plano, Texas", keyword: "plano_texas" },
    { id: 71, city: "Henderson, Nevada", keyword: "henderson_nevada" },
    { id: 72, city: "Lincoln, Nebraska", keyword: "lincoln_nebraska" },
    { id: 73, city: "Buffalo, New York", keyword: "buffalo_new_york" },
    { id: 74, city: "Fort Wayne, Indiana", keyword: "fort_wayne_indiana" },
    { id: 75, city: "Jersey City, New Jersey", keyword: "jersey_city_new_jersey" },
    { id: 76, city: "Chula Vista, California", keyword: "chula_vista_california" },
    { id: 77, city: "Orlando, Florida", keyword: "orlando_florida" },
    { id: 78, city: "St. Petersburg, Florida", keyword: "st_petersburg_florida" },
    { id: 79, city: "Norfolk, Virginia", keyword: "norfolk_virginia" },
    { id: 80, city: "Chandler, Arizona", keyword: "chandler_arizona" },
    { id: 81, city: "Laredo, Texas", keyword: "laredo_texas" },
    { id: 82, city: "Madison, Wisconsin", keyword: "madison_wisconsin" },
    { id: 83, city: "Durham, North Carolina", keyword: "durham_north_carolina" },
    { id: 84, city: "Lubbock, Texas", keyword: "lubbock_texas" },
    { id: 85, city: "Winston-Salem, North Carolina", keyword: "winston_salem_north_carolina" },
    { id: 86, city: "Garland, Texas", keyword: "garland_texas" },
    { id: 87, city: "Glendale, Arizona", keyword: "glendale_arizona" },
    { id: 88, city: "Hialeah, Florida", keyword: "hialeah_florida" },
    { id: 89, city: "Reno, Nevada", keyword: "reno_nevada" },
    { id: 90, city: "Baton Rouge, Louisiana", keyword: "baton_rouge_louisiana" },
    { id: 91, city: "Irvine, California", keyword: "irvine_california" },
    { id: 92, city: "Chesapeake, Virginia", keyword: "chesapeake_virginia" },
    { id: 93, city: "Irving, Texas", keyword: "irving_texas" },
    { id: 94, city: "Scottsdale, Arizona", keyword: "scottsdale_arizona" },
    { id: 95, city: "North Las Vegas, Nevada", keyword: "north_las_vegas_nevada" },
    { id: 96, city: "Fremont, California", keyword: "fremont_california" },
    { id: 97, city: "Gilbert, Arizona", keyword: "gilbert_arizona" },
    { id: 98, city: "San Bernardino, California", keyword: "san_bernardino_california" },
    { id: 99, city: "Boise City, Idaho", keyword: "boise_city_idaho" },
    { id: 100, city: "Birmingham, Alabama", keyword: "birmingham_alabama" },
    { id: 101, city: "Rochester, New York", keyword: "rochester_new_york" },
    { id: 102, city: "Richmond, Virginia", keyword: "richmond_virginia" },
    { id: 103, city: "Spokane, Washington", keyword: "spokane_washington" },
    { id: 104, city: "Des Moines, Iowa", keyword: "des_moines_iowa" },
    { id: 105, city: "Montgomery, Alabama", keyword: "montgomery_alabama" },
    { id: 106, city: "Modesto, California", keyword: "modesto_california" },
    { id: 107, city: "Fayetteville, North Carolina", keyword: "fayetteville_north_carolina" },
    { id: 108, city: "Tacoma, Washington", keyword: "tacoma_washington" },
    { id: 109, city: "Shreveport, Louisiana", keyword: "shreveport_louisiana" },
    { id: 110, city: "Fontana, California", keyword: "fontana_california" },
    { id: 111, city: "Oxnard, California", keyword: "oxnard_california" },
    { id: 112, city: "Aurora, Illinois", keyword: "aurora_illinois" },
    { id: 113, city: "Moreno Valley, California", keyword: "moreno_valley_california" },
    { id: 114, city: "Akron, Ohio", keyword: "akron_ohio" },
    { id: 115, city: "Yonkers, New York", keyword: "yonkers_new_york" },
    { id: 116, city: "Columbus, Georgia", keyword: "columbus_georgia" },
    { id: 117, city: "Augusta-Richmond, Georgia", keyword: "augusta_richmond_georgia" },
    { id: 118, city: "Little Rock, Arkansas", keyword: "little_rock_arkansas" },
    { id: 119, city: "Amarillo, Texas", keyword: "amarillo_texas" },
    { id: 120, city: "Mobile, Alabama", keyword: "mobile_alabama" },
    { id: 121, city: "Huntington Beach, California", keyword: "huntington_beach_california" },
    { id: 122, city: "Glendale, California", keyword: "glendale_california" },
    { id: 123, city: "Grand Rapids, Michigan", keyword: "grand_rapids_michigan" },
    { id: 124, city: "Salt Lake City, Utah", keyword: "salt_lake_city_utah" },
    { id: 125, city: "Tallahassee, Florida", keyword: "tallahassee_florida" },
    { id: 126, city: "Huntsville, Alabama", keyword: "huntsville_alabama" },
    { id: 127, city: "Worcester, Massachusetts", keyword: "worcester_massachusetts" },
    { id: 128, city: "Knoxville, Tennessee", keyword: "knoxville_tennessee" },
    { id: 129, city: "Grand Prairie, Texas", keyword: "grand_prairie_texas" },
    { id: 130, city: "Newport News, Virginia", keyword: "newport_news_virginia" },
    { id: 131, city: "Brownsville, Texas", keyword: "brownsville_texas" },
    { id: 132, city: "Santa Clarita, California", keyword: "santa_clarita_california" },
    { id: 133, city: "Overland Park, Kansas", keyword: "overland_park_kansas" },
    { id: 134, city: "Providence, Rhode Island", keyword: "providence_rhode_island" },
    { id: 135, city: "Jackson, Mississippi", keyword: "jackson_mississippi" },
    { id: 136, city: "Garden Grove, California", keyword: "garden_grove_california" },
    { id: 137, city: "Oceanside, California", keyword: "oceanside_california" },
    { id: 138, city: "Chattanooga, Tennessee", keyword: "chattanooga_tennessee" },
    { id: 139, city: "Fort Lauderdale, Florida", keyword: "fort_lauderdale_florida" },
    { id: 140, city: "Rancho Cucamonga, California", keyword: "rancho_cucamonga_california" },
    { id: 141, city: "Santa Rosa, California", keyword: "santa_rosa_california" },
    { id: 142, city: "Port St. Lucie, Florida", keyword: "port_st_lucie_florida" },
    { id: 143, city: "Ontario, California", keyword: "ontario_california" },
    { id: 144, city: "Tempe, Arizona", keyword: "tempe_arizona" },
    { id: 145, city: "Vancouver, Washington", keyword: "vancouver_washington" },
    { id: 146, city: "Springfield, Missouri", keyword: "springfield_missouri" },
    { id: 147, city: "Cape Coral, Florida", keyword: "cape_coral_florida" },
    { id: 148, city: "Pembroke Pines, Florida", keyword: "pembroke_pines_florida" },
    { id: 149, city: "Sioux Falls, South Dakota", keyword: "sioux_falls_south_dakota" },
    { id: 150, city: "Peoria, Arizona", keyword: "peoria_arizona" },
    { id: 151, city: "Lancaster, California", keyword: "lancaster_california" },
    { id: 152, city: "Elk Grove, California", keyword: "elk_grove_california" },
    { id: 153, city: "Corona, California", keyword: "corona_california" },
    { id: 154, city: "Eugene, Oregon", keyword: "eugene_oregon" },
    { id: 155, city: "Salem, Oregon", keyword: "salem_oregon" },
    { id: 156, city: "Palmdale, California", keyword: "palmdale_california" },
    { id: 157, city: "Salinas, California", keyword: "salinas_california" },
    { id: 158, city: "Springfield, Massachusetts", keyword: "springfield_massachusetts" },
    { id: 159, city: "Pasadena, Texas", keyword: "pasadena_texas" },
    { id: 160, city: "Rockford, Illinois", keyword: "rockford_illinois" },
    { id: 161, city: "Pomona, California", keyword: "pomona_california" },
    { id: 162, city: "Hayward, California", keyword: "hayward_california" },
    { id: 163, city: "Fort Collins, Colorado", keyword: "fort_collins_colorado" },
    { id: 164, city: "Joliet, Illinois", keyword: "joliet_illinois" },
    { id: 165, city: "Escondido, California", keyword: "escondido_california" },
    { id: 166, city: "Kansas City, Kansas", keyword: "kansas_city_kansas" },
    { id: 167, city: "Torrance, California", keyword: "torrance_california" },
    { id: 168, city: "Bridgeport, Connecticut", keyword: "bridgeport_connecticut" },
    { id: 169, city: "Alexandria, Virginia", keyword: "alexandria_virginia" },
    { id: 170, city: "Sunnyvale, California", keyword: "sunnyvale_california" },
    { id: 171, city: "Cary, North Carolina", keyword: "cary_north_carolina" },
    { id: 172, city: "Lakewood, Colorado", keyword: "lakewood_colorado" },
    { id: 173, city: "Hollywood, Florida", keyword: "hollywood_florida" },
    { id: 174, city: "Paterson, New Jersey", keyword: "paterson_new_jersey" },
    { id: 175, city: "Syracuse, New York", keyword: "syracuse_new_york" },
    { id: 176, city: "Naperville, Illinois", keyword: "naperville_illinois" },
    { id: 177, city: "McKinney, Texas", keyword: "mckinney_texas" },
    { id: 178, city: "Mesquite, Texas", keyword: "mesquite_texas" },
    { id: 179, city: "Clarksville, Tennessee", keyword: "clarksville_tennessee" },
    { id: 180, city: "Savannah, Georgia", keyword: "savannah_georgia" },
    { id: 181, city: "Dayton, Ohio", keyword: "dayton_ohio" },
    { id: 182, city: "Orange, California", keyword: "orange_california" },
    { id: 183, city: "Fullerton, California", keyword: "fullerton_california" },
    { id: 184, city: "Pasadena, California", keyword: "pasadena_california" },
    { id: 185, city: "Hampton, Virginia", keyword: "hampton_virginia" },
    { id: 186, city: "McAllen, Texas", keyword: "mcallen_texas" },
    { id: 187, city: "Killeen, Texas", keyword: "killeen_texas" },
    { id: 188, city: "Warren, Michigan", keyword: "warren_michigan" },
    { id: 189, city: "West Valley City, Utah", keyword: "west_valley_city_utah" },
    { id: 190, city: "Columbia, South Carolina", keyword: "columbia_south_carolina" },
    { id: 191, city: "New Haven, Connecticut", keyword: "new_haven_connecticut" },
    { id: 192, city: "Sterling Heights, Michigan", keyword: "sterling_heights_michigan" },
    { id: 193, city: "Olathe, Kansas", keyword: "olathe_kansas" },
    { id: 194, city: "Miramar, Florida", keyword: "miramar_florida" },
    { id: 195, city: "Thousand Oaks, California", keyword: "thousand_oaks_california" },
    { id: 196, city: "Frisco, Texas", keyword: "frisco_texas" },
    { id: 197, city: "Cedar Rapids, Iowa", keyword: "cedar_rapids_iowa" },
    { id: 198, city: "Topeka, Kansas", keyword: "topeka_kansas" },
    { id: 199, city: "Visalia, California", keyword: "visalia_california" },
    { id: 200, city: "Waco, Texas", keyword: "waco_texas" },
    { id: 201, city: "Elizabeth, New Jersey", keyword: "elizabeth_new_jersey" },
    { id: 202, city: "Bellevue, Washington", keyword: "bellevue_washington" },
    { id: 203, city: "Gainesville, Florida", keyword: "gainesville_florida" },
    { id: 204, city: "Simi Valley, California", keyword: "simi_valley_california" },
    { id: 205, city: "Charleston, South Carolina", keyword: "charleston_south_carolina" },
    { id: 206, city: "Carrollton, Texas", keyword: "carrollton_texas" },
    { id: 207, city: "Coral Springs, Florida", keyword: "coral_springs_florida" },
    { id: 208, city: "Stamford, Connecticut", keyword: "stamford_connecticut" },
    { id: 209, city: "Hartford, Connecticut", keyword: "hartford_connecticut" },
    { id: 210, city: "Concord, California", keyword: "concord_california" },
    { id: 211, city: "Roseville, California", keyword: "roseville_california" },
    { id: 212, city: "Thornton, Colorado", keyword: "thornton_colorado" },
    { id: 213, city: "Kent, Washington", keyword: "kent_washington" },
    { id: 214, city: "Lafayette, Louisiana", keyword: "lafayette_louisiana" },
    { id: 215, city: "Surprise, Arizona", keyword: "surprise_arizona" },
    { id: 216, city: "Denton, Texas", keyword: "denton_texas" },
    { id: 217, city: "Victorville, California", keyword: "victorville_california" },
    { id: 218, city: "Evansville, Indiana", keyword: "evansville_indiana" },
    { id: 219, city: "Midland, Texas", keyword: "midland_texas" },
    { id: 220, city: "Santa Clara, California", keyword: "santa_clara_california" },
    { id: 221, city: "Athens, Georgia", keyword: "athens_georgia" },
    { id: 222, city: "Allentown, Pennsylvania", keyword: "allentown_pennsylvania" },
    { id: 223, city: "Abilene, Texas", keyword: "abilene_texas" },
    { id: 224, city: "Beaumont, Texas", keyword: "beaumont_texas" },
    { id: 225, city: "Vallejo, California", keyword: "vallejo_california" },
    { id: 226, city: "Independence, Missouri", keyword: "independence_missouri" },
    { id: 227, city: "Springfield, Illinois", keyword: "springfield_illinois" },
    { id: 228, city: "Ann Arbor, Michigan", keyword: "ann_arbor_michigan" },
    { id: 229, city: "Provo, Utah", keyword: "provo_utah" },
    { id: 230, city: "Peoria, Illinois", keyword: "peoria_illinois" },
    { id: 231, city: "Norman, Oklahoma", keyword: "norman_oklahoma" },
    { id: 232, city: "Berkeley, California", keyword: "berkeley_california" },
    { id: 233, city: "El Monte, California", keyword: "el_monte_california" },
    { id: 234, city: "Murfreesboro, Tennessee", keyword: "murfreesboro_tennessee" },
    { id: 235, city: "Lansing, Michigan", keyword: "lansing_michigan" },
    { id: 236, city: "Columbia, Missouri", keyword: "columbia_missouri" },
    { id: 237, city: "Downey, California", keyword: "downey_california" },
    { id: 238, city: "Costa Mesa, California", keyword: "costa_mesa_california" },
    { id: 239, city: "Inglewood, California", keyword: "inglewood_california" },
    { id: 240, city: "Miami Gardens, Florida", keyword: "miami_gardens_florida" },
    { id: 241, city: "Manchester, New Hampshire", keyword: "manchester_new_hampshire" },
    { id: 242, city: "Elgin, Illinois", keyword: "elgin_illinois" },
    { id: 243, city: "Wilmington, North Carolina", keyword: "wilmington_north_carolina" },
    { id: 244, city: "Waterbury, Connecticut", keyword: "waterbury_connecticut" },
    { id: 245, city: "Fargo, North Dakota", keyword: "fargo_north_dakota" },
    { id: 246, city: "Arvada, Colorado", keyword: "arvada_colorado" },
    { id: 247, city: "Carlsbad, California", keyword: "carlsbad_california" },
    { id: 248, city: "Westminster, Colorado", keyword: "westminster_colorado" },
    { id: 249, city: "Rochester, Minnesota", keyword: "rochester_minnesota" },
    { id: 250, city: "Gresham, Oregon", keyword: "gresham_oregon" },
    { id: 251, city: "Clearwater, Florida", keyword: "clearwater_florida" },
    { id: 252, city: "Lowell, Massachusetts", keyword: "lowell_massachusetts" },
    { id: 253, city: "West Jordan, Utah", keyword: "west_jordan_utah" },
    { id: 254, city: "Pueblo, Colorado", keyword: "pueblo_colorado" },
    { id: 255, city: "San Buenaventura, California", keyword: "san_buenaventura_california" },
    { id: 256, city: "Fairfield, California", keyword: "fairfield_california" },
    { id: 257, city: "West Covina, California", keyword: "west_covina_california" },
    { id: 258, city: "Billings, Montana", keyword: "billings_montana" },
    { id: 259, city: "Murrieta, California", keyword: "murrieta_california" },
    { id: 260, city: "High Point, North Carolina", keyword: "high_point_north_carolina" },
    { id: 261, city: "Round Rock, Texas", keyword: "round_rock_texas" },
    { id: 262, city: "Richmond, California", keyword: "richmond_california" },
    { id: 263, city: "Cambridge, Massachusetts", keyword: "cambridge_massachusetts" },
    { id: 264, city: "Norwalk, California", keyword: "norwalk_california" },
    { id: 265, city: "Odessa, Texas", keyword: "odessa_texas" },
    { id: 266, city: "Antioch, California", keyword: "antioch_california" },
    { id: 267, city: "Temecula, California", keyword: "temecula_california" },
    { id: 268, city: "Green Bay, Wisconsin", keyword: "green_bay_wisconsin" },
    { id: 269, city: "Everett, Washington", keyword: "everett_washington" },
    { id: 270, city: "Wichita Falls, Texas", keyword: "wichita_falls_texas" },
    { id: 271, city: "Burbank, California", keyword: "burbank_california" },
    { id: 272, city: "Palm Bay, Florida", keyword: "palm_bay_florida" },
    { id: 273, city: "Centennial, Colorado", keyword: "centennial_colorado" },
    { id: 274, city: "Daly City, California", keyword: "daly_city_california" },
    { id: 275, city: "Richardson, Texas", keyword: "richardson_texas" },
    { id: 276, city: "Pompano Beach, Florida", keyword: "pompano_beach_florida" },
    { id: 277, city: "Broken Arrow, Oklahoma", keyword: "broken_arrow_oklahoma" },
    { id: 278, city: "North Charleston, South Carolina", keyword: "north_charleston_south_carolina" },
    { id: 279, city: "West Palm Beach, Florida", keyword: "west_palm_beach_florida" },
    { id: 280, city: "Boulder, Colorado", keyword: "boulder_colorado" },
    { id: 281, city: "Rialto, California", keyword: "rialto_california" },
    { id: 282, city: "Santa Maria, California", keyword: "santa_maria_california" },
    { id: 283, city: "El Cajon, California", keyword: "el_cajon_california" },
    { id: 284, city: "Davenport, Iowa", keyword: "davenport_iowa" },
    { id: 285, city: "Las Cruces, New Mexico", keyword: "las_cruces_new_mexico" },
    { id: 286, city: "Erie, Pennsylvania", keyword: "erie_pennsylvania" },
    { id: 287, city: "South Bend, Indiana", keyword: "south_bend_indiana" },
    { id: 288, city: "Flint, Michigan", keyword: "flint_michigan" },
    { id: 289, city: "Kenosha, Wisconsin", keyword: "kenosha_wisconsin" },
    { id: 290, city: "Lakeland, Florida", keyword: "lakeland_florida" },
    { id: 291, city: "San Mateo, California", keyword: "san_mateo_california" },
    { id: 292, city: "Lewisville, Texas", keyword: "lewisville_texas" },
    { id: 293, city: "Sandy Springs, Georgia", keyword: "sandy_springs_georgia" },
    { id: 294, city: "Tyler, Texas", keyword: "tyler_texas" },
    { id: 295, city: "Clovis, California", keyword: "clovis_california" },
    { id: 296, city: "Lawton, Oklahoma", keyword: "lawton_oklahoma" },
    { id: 297, city: "Albany, New York", keyword: "albany_new_york" },
    { id: 298, city: "College Station, Texas", keyword: "college_station_texas" },
    { id: 299, city: "Compton, California", keyword: "compton_california" },
    { id: 300, city: "Roanoke, Virginia", keyword: "roanoke_virginia" },
];

  options = { 
    hintText: "Type in a city", 
    animateDropdown: false,
    searchDelay: 100,
    tokenLimit: 3,
    resultsLimit: 5,
    preventDuplicates: true,
    propertyToSearch: "city"
  };

  $("#searchbar").tokenInput(cities, options);
});

